version: 2
updates:
  - package-ecosystem: "bundler" 
    directory: "/sample" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-patch"]
